{% set name = "apache-airflow-providers-smtp" %}
{% set version = "2.1.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_smtp-{{ version }}.tar.gz
  sha256: c15caa55697c6c95a229944f1fe96d30134adfa425f74afeff12cdb8d4d061ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-compat >=1.6.1

test:
  imports:
    - airflow.providers.smtp
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-smtp for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: src/airflow/providers/smtp/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-smtp/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
